import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import styled from 'styled-components';

import { KeywordTag } from '../components/Filter';
import { HeaderBar } from '../components/Header';
import { ProjectSpace } from '../components/Projects';
import WelcomeBox from '../components/WelcomeBox';
import CenterLayout from '../layouts/CenterLayout';
import ProjectList from './components/ProjectList';
import {
  Body,
  Header,
  Landing,
  List,
  Main,
  Page,
  Projectblocks,
  Projectbutton,
  Projectfilterarea,
  Projectgrid,
  Projectlist,
  Projectwriteup,
  RedLine,
  StyledALink,
  StyledLink,
  Textbox,
  Writeup,
  WriteupBlock,
  WriteupTitles,
  WriteupWrapper,
  YellowLine,
} from './styled';

const Home: NextPage = function () {
  const arr = [{ writeup: 'blah blah blah', link: 'hello' }];

  return (
    <CenterLayout>
      <Head>
        <title>andrew-projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        {/* header is 10vh */}

        <HeaderBar />
        <Body>
          <Page height={'55vh'}>
            <Landing>
              <Textbox justifyContent={'center'}>
                <h1>Projects</h1>
              </Textbox>
              <Image
                src="/placeholder.png"
                height={330}
                width={330}
                alt="My face"
              ></Image>
            </Landing>
          </Page>
          <Page height={'120vh'}>
            <ProjectSpace />
          </Page>
        </Body>
      </Main>
    </CenterLayout>
  );
};

export default Home;
